# Generated by Django 5.0.1 on 2024-01-10 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0008_remove_dashboardstats_total_blue_cards"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboardstats",
            name="total_goals",
            field=models.IntegerField(null=True),
        ),
    ]
