# Generated by Django 5.0.1 on 2024-01-10 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0009_alter_dashboardstats_total_goals"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboardstats",
            name="total_assists",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="dashboardstats",
            name="total_clean_sheets",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="dashboardstats",
            name="total_red_cards",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="dashboardstats",
            name="total_saves",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="dashboardstats",
            name="total_yellow_cards",
            field=models.IntegerField(null=True),
        ),
    ]
